### PR TITLE
Added 1 new string 

### PR DESCRIPTION
**Pull request by SlowLife1661**
1 new string

Viewing character:

### CODE REVIEW

**Comment by ImRodry** [comment]
Why would this be in general?

**Comment by SlowLife1661** [comment]
Kek ok I will add strings for my presence

**Comment by ImRodry** [comment]
What’s your presence called?

**Comment by SlowLife1661** [comment]
I mean I'm working on new presence called Anime Planet

**Comment by ImRodry** [comment]
You can only add strings for it if it reaches more than 1k users :/

**Comment by SlowLife1661** [comment]
🥶

**Comment by SlowLife1661** [comment]
Close this please

**Pull request closed without merging**
